<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Payroll.Classifications\Payroll.Classifications.csproj" />
    <ProjectReference Include="..\Payroll.Core\Payroll.Core.csproj" />
    <ProjectReference Include="..\Payroll.Schedules\Payroll.Schedules.csproj" />
    <ProjectReference Include="..\Payroll.Transactions\Payroll.Transactions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
